### ISSUE TITLE
Admin home lists the same driver for all trips

### ISSUE THREAD

**Issue by AndyRiedel** [JasonSolace/drive-and-doc#53]
Steps to replicate:
1. Login with user "admin"
2. On redirect to home, observe that all active trips show "John Doe" as the driver
3.  Would expect to see either "Test2 User2" or "Jane Doe" for all active trips for company 1

**Comment by JasonSolace** [comment]
Added a patch to alleviate this issue for now. Even if this gets fixed, my patch should hold up.

**Comment by AndyRiedel** [comment]
@JasonSolace  FYI this issue is fixed
